---
- name: Check if the "reboot" tag was specified"
  ansible.builtin.set_fact:
    reboot_required: true
  when: reboot in ansible_run_tags

- name: Reboot if necessary
  ansible.builtin.reboot:
    name: Sending system down for reboot now!
    reboot_timeout: 1200
  become: true
  when: reboot_required
