---
- name: "Create backups dir if it doesn't exist"
  file:
    path: "{{ minecraft.server.backup_dir }}"
    state: directory
    owner: "{{ minecraft.user.username }}"
    group: "{{ minecraft.user.username }}"

- name: "Generate timestamp for backup file name"
  shell: date +"%m-%d-%Y-%H-%M-%S"
  register: mc_backup_timestamp

- name: "Set name for backup file"
  set_fact:
    mc_backup_file_name: "foolcraft3-v1.6-{{ mc_backup_timestamp.stdout }}.tar"

- name: "Perform archive backup"
  shell: "tar -cvf {{ minecraft.server.backup_dir }}/{{ mc_backup_file_name }} ~/foolcraft3-v1.6/"
  become: yes
  become_user: "{{ minecraft.user.username }}"

- name: "Compress archive"
  shell: "gzip {{ minecraft.server.backup_dir }}/{{ mc_backup_file_name }}"
  become: yes
  become_user: "{{ minecraft.user.username }}"
...
