---
reboot_required: false

installation_user: arkserver
user_home_folder: "/home/{{ installation_user }}"

lgsm_script_path: "{{ user_home_folder }}/linuxgsm.sh"
install_script_binary_path: "{{ user_home_folder }}/{{ installation_user }}"

firewall_ports:
  - 25147
  - 27015
  - 27031
  - 27032
  - 27033
  - 27034
  - 27035
  - 27036

package_dependencies:
  - curl
  - wget
  - file
  - tar
  - bzip2
  - gzip
  - unzip
  - bsdmainutils
  - python3
  - util-linux
  - ca-certificates
  - binutils
  - bc
  - jq
  - tmux
  - netcat
  - lib32gcc1
  - lib32stdc++6
  - libsdl2-2.0-0:i386
