---
reboot_required: false

installation_user: mcserver
install_script_binary_path: /home/{{ installation_user }}/{{ installation_user }}

firewall_ports:
  - 25565

package_dependencies:
  - curl
  - wget
  - tar
  - bzip2
  - gzip
  - unzip
  - python3
  - binutils
  - bc
  - jq
  - tmux
  - openjdk-17-jre
