---
reboot_required: false

installation_user: mcserver
user_home_folder: "/home/{{ installation_user }}"

lgsm_script_path: "{{ user_home_folder }}/linuxgsm.sh"
install_script_binary_path: "{{ user_home_folder }}/{{ installation_user }}"

firewall_ports:
  - 25565

package_dependencies:
  - curl
  - wget
  - tar
  - bzip2
  - gzip
  - unzip
  - python3
  - binutils
  - bc
  - jq
  - tmux
  - openjdk-17-jre
