---
minecraft:
  user: 
    username: "minecraft"
    home_dir: "/home/minecraft"
  server:
    installed_dir: "/home/minecraft/foolcraft3-v1.6"
    backup_dir: "/home/minecraft/backups"
    forge_jar: "forge-1.12.2-14.23.5.2768-universal.jar"
    screen_session_name: "minecraft-jvm-bg-proc"
  jvm:
    min_memory: "8G"
    max_memory: "8G"
...
