---
installation_user: mcserver

firewall_ports:
  - 25565

package_dependencies:
  - bc
  - binutils
  - bsdmainutils
  - bzip2
  - curl
  - distro-info
  - gzip
  - jq
  - lib32gcc-s1
  - lib32stdc++6
  - libsdl2-2.0-0:i386
  - openjdk-17-jre
  - python3
  - tar
  - tmux
  - unzip
  - wget
