---
installation_user: vhserver

firewall_ports:
  - 2456

package_dependencies:
  - bc
  - binutils
  - bsdmainutils
  - bzip2
  - ca-certificates
  - curl
  - distro-info
  - gzip
  - jq
  - lib32gcc-s1
  - lib32stdc++6
  - libsdl2-2.0-0
  - libc6-dev
  - libsdl2-2.0-0:i386
  - netcat-openbsd
  - python3
  - tar
  - tmux
  - unzip
  - util-linux
  - wget
