---
- name: Backup lgsm server
  ansible.builtin.command:
    cmd: "{{ install_script_binary_path }} backup"
    chdir: "{{ user_home_folder }}"
  become: true
  become_user: "{{ installation_user }}"
  register: backup_result
  failed_when: backup_result.rc not in [0, 3]

- name: Get list of backups on the LGSM server
  ansible.builtin.find:
    paths: "{{ lgsm_backup_path }}"
  register: backup_file_list
  become: true
  become_user: "{{ installation_user }}"

# Rsync does not seem to support transferring between two remote hosts
# Therefore use scp with the -3 option instead
# The controller has ssh keys authorized on both hosts
# But neither remote host has an authorized key on the other
- name: Upload files to remote backup host
  ansible.builtin.command:
    cmd: >-
      scp -3
      {{ installation_user }}@{{ hostvars[inventory_hostname].ansible_host }}:{{ item }}
      root@{{ hostvars['backuphost'].ansible_host }}:{{ remote_backup_path }}/{{ item | basename }}
  with_items: "{{ backup_file_list.files | map(attribute='path') | list }}"
  delegate_to: localhost
