---
- name: Create lgsm server user
  ansible.builtin.user:
    name: "{{ installation_user }}"
    state: present

- name: Run commands as new user
  become: true
  become_user: "{{ installation_user }}"
  block:
    - name: Download lgsm installation script from website
      ansible.builtin.get_url:
        url: https://linuxgsm.sh
        dest: "{{ lgsm_script_path }}"
        mode: "0750"

    - name: Install the binary for the specific server
      ansible.builtin.command:
        cmd: bash {{ lgsm_script_path }} {{ installation_user }}
        chdir: "{{ user_home_folder }}"

    - name: Execute lgsm install
      ansible.builtin.command: "{{ install_script_binary_path }} auto-install"

    - name: Create backup log directory
      ansible.builtin.file:
        path: "{{ backup_log_directory }}"
        state: directory
        mode: "0640"

- name: Include cron tasks
  ansible.builtin.include_tasks: cron.yaml

- name: Include systemd tasks
  ansible.builtin.include_tasks: systemd.yaml
