---
- name: Start LGSM server
  ansible.builtin.command:
    cmd: "{{ install_script_binary_path }} start"
    chdir: "{{ user_home_folder }}"
  become: true
  become_user: "{{ installation_user }}"
  register: start_server
  failed_when: start_server.rc == 1 or start_server.rc > 2
