---
- name: Stop lgsm server
  ansible.builtin.command:
    cmd: "{{ install_script_binary_path }} stop"
    chdir: "{{ user_home_folder }}"
  become: true
  become_user: "{{ installation_user }}"
  register: stop_result
  failed_when: stop_result.rc not in [0,2]
