---
- name: Update lgsm server
  ansible.builtin.command:
    cmd: "{{ install_script_binary_path }} update"
    chdir: "{{ user_home_folder }}"
  become: true
  become_user: "{{ installation_user }}"
