---
- name: 'Backup Minecraft Server'
  become: true
  become_user: 'minecraft'
  archive:
    path: '~/foolcraft3'
    dest: '~/backups/foolcraft3-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.tar.gz'
    format: 'gz'
  tags: minecraft
...