---
all:
  children:
    ubuntu:
        hosts: 
          testbed:
            ansible_port: 22
            ansible_host: 192.168.10.67
            ansible_user: user
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
          minecraft:
            ansible_port: 22
            ansible_host: 192.168.10.32
            ansible_user: user
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ark:
            ansible_port: 22
            ansible_host: 192.168.10.69
            ansible_user: user
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
...